
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import {Navbar, SidebarLeft, SidebarRight} from "@/components";
import {Providers} from "@/providers";
import ProviderThemes from "@/providers/ProviderThemes";
import {ProvidersState} from "@/settings/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PlaylistSync",
  description: "Generated by oqpa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning={true}>
      <body className={"bg-light-m dark:bg-dark-m"}>
            <ProvidersState>
                <ProviderThemes>
                    <Providers>
                        <div>
                            <SidebarLeft/>
                            <main
                                className={"min-w-[90%] flex flex-col justify-between  bg-light-m dark:bg-dark-m h-screen"}
                            >
                                <div className="w-full">
                                    <Navbar/>
                                </div>
                                <div className="md:min-w-[50%] flex flex-row h-full w-full md:mt-16 padding-container bg-light-m dark:bg-dark-m ">
                                    {children}
                                    <div className={"hidden md:flex max-w-[22%]"}>
                                        <SidebarRight/>
                                    </div>
                                </div>
                            </main>
                        </div>
                    </Providers>
                </ProviderThemes>
            </ProvidersState>
      </body>
    </html>
  );
}
